rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: master
  isAdminEnforced: true
  requiredStatusCheckContexts:
    - 'cla/google'
    - 'codecov/patch'
    - 'codecov/project'
    - 'conventionalcommits.org'
    - 'docs'
    - 'mypy'
    - 'showcase'
    - 'showcase-mtls'
    - 'showcase-unit'
    - 'showcase-unit-alternative-templates'
    - 'showcase-unit-add-iam-methods'
    - 'showcase-mypy'
    - 'showcase-mypy-alternative-templates'
    - 'unit'
    - 'style-check'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: actools
    permission: admin
  - team: yoshi-python
    permission: push
  - team: actools-python
    permission: push
