rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: master
  isAdminEnforced: true
  requiredStatusCheckContexts:
    - 'cla/google'
    - 'docs'
    - 'mypy'
    - 'showcase (showcase)'
    - 'showcase (showcase_alternative_templates)'
    - 'showcase-mtls (showcase_mtls)'
    - 'showcase-mtls (showcase_mtls_alternative_templates)'
    - 'showcase-mypy'
    - 'showcase-mypy (_alternative_templates)'
    - 'showcase-unit (3.6)'
    - 'showcase-unit (3.7)'
    - 'showcase-unit (3.7, _alternative_templates)'
    - 'showcase-unit (3.8)'
    - 'showcase-unit (3.8, _alternative_templates)'
    - 'showcase-unit (3.9)'
    - 'showcase-unit (3.9, _alternative_templates)'
    - 'showcase-unit-add-iam-methods'
    - 'integration'
    - 'style-check'
    - 'unit (3.6)'
    - 'unit (3.7)'
    - 'unit (3.8)'
    - 'unit (3.9)'
    - 'fragment (3.6)'
    - 'fragment (3.7)'
    - 'fragment (3.8)'
    - 'fragment (3.9)'
    - 'fragment (3.7, _alternative_templates)'
    - 'fragment (3.8, _alternative_templates)'
    - 'fragment (3.9, _alternative_templates)'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: actools
    permission: admin
  - team: yoshi-python
    permission: push
  - team: actools-python
    permission: push
