# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/client.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/api/client.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x17google/api/client.proto\x1a google/protobuf/descriptor.proto\"B\n\rDocumentation\x12\x0f\n\x07tagline\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\")\n\tCopyright\x12\x0e\n\x06\x65ntity\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\t\",\n\x07License\x12\x14\n\x0clicense_name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"\xc6\x01\n\x06\x43lient\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x03(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12%\n\rdocumentation\x18\n \x01(\x0b\x32\x0e.Documentation\x12\x1d\n\tcopyright\x18\x0b \x01(\x0b\x32\n.Copyright\x12\x19\n\x07license\x18\x0c \x01(\x0b\x32\x08.License\x12\x14\n\x0cservice_host\x18\x14 \x01(\t\x12\x13\n\x0b\x61uth_scopes\x18\x15 \x03(\t:7\n\x06\x63lient\x12\x1c.google.protobuf.FileOptions\x18\xd0\x86\x03 \x01(\x0b\x32\x07.Clientb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


CLIENT_FIELD_NUMBER = 50000
client = _descriptor.FieldDescriptor(
  name='client', full_name='client', index=0,
  number=50000, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_DOCUMENTATION = _descriptor.Descriptor(
  name='Documentation',
  full_name='Documentation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tagline', full_name='Documentation.tagline', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='Documentation.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='Documentation.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=127,
)


_COPYRIGHT = _descriptor.Descriptor(
  name='Copyright',
  full_name='Copyright',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity', full_name='Copyright.entity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='year', full_name='Copyright.year', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=170,
)


_LICENSE = _descriptor.Descriptor(
  name='License',
  full_name='License',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='license_name', full_name='License.license_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='License.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=216,
)


_CLIENT = _descriptor.Descriptor(
  name='Client',
  full_name='Client',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Client.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='Client.namespace', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='Client.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='documentation', full_name='Client.documentation', index=3,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='copyright', full_name='Client.copyright', index=4,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='license', full_name='Client.license', index=5,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service_host', full_name='Client.service_host', index=6,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auth_scopes', full_name='Client.auth_scopes', index=7,
      number=21, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=417,
)

_CLIENT.fields_by_name['documentation'].message_type = _DOCUMENTATION
_CLIENT.fields_by_name['copyright'].message_type = _COPYRIGHT
_CLIENT.fields_by_name['license'].message_type = _LICENSE
DESCRIPTOR.message_types_by_name['Documentation'] = _DOCUMENTATION
DESCRIPTOR.message_types_by_name['Copyright'] = _COPYRIGHT
DESCRIPTOR.message_types_by_name['License'] = _LICENSE
DESCRIPTOR.message_types_by_name['Client'] = _CLIENT
DESCRIPTOR.extensions_by_name['client'] = client

Documentation = _reflection.GeneratedProtocolMessageType('Documentation', (_message.Message,), dict(
  DESCRIPTOR = _DOCUMENTATION,
  __module__ = 'google.api.client_pb2'
  # @@protoc_insertion_point(class_scope:Documentation)
  ))
_sym_db.RegisterMessage(Documentation)

Copyright = _reflection.GeneratedProtocolMessageType('Copyright', (_message.Message,), dict(
  DESCRIPTOR = _COPYRIGHT,
  __module__ = 'google.api.client_pb2'
  # @@protoc_insertion_point(class_scope:Copyright)
  ))
_sym_db.RegisterMessage(Copyright)

License = _reflection.GeneratedProtocolMessageType('License', (_message.Message,), dict(
  DESCRIPTOR = _LICENSE,
  __module__ = 'google.api.client_pb2'
  # @@protoc_insertion_point(class_scope:License)
  ))
_sym_db.RegisterMessage(License)

Client = _reflection.GeneratedProtocolMessageType('Client', (_message.Message,), dict(
  DESCRIPTOR = _CLIENT,
  __module__ = 'google.api.client_pb2'
  # @@protoc_insertion_point(class_scope:Client)
  ))
_sym_db.RegisterMessage(Client)

client.message_type = _CLIENT
google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(client)

# @@protoc_insertion_point(module_scope)
