# -*- coding: utf-8 -*-
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import google.auth
try:
    import aiohttp # type: ignore
    from google.auth.aio.transport.sessions import AsyncAuthorizedSession # type: ignore
except ImportError as e:  # pragma: NO COVER
    raise ImportError("async rest transport requires google-auth >= 2.35.0 with aiohttp extra. Install google-auth with the aiohttp extra using `pip install google-auth[aiohttp]==2.35.0`.") from e

from google.auth.aio import credentials as ga_credentials_async  # type: ignore

from google.api_core import exceptions as core_exceptions
from google.api_core import gapic_v1
from google.api_core import retry_async as retries
from google.api_core import rest_helpers
from google.api_core import rest_streaming_async  # type: ignore

try:
    from google.api_core import rest_streaming_async # type: ignore
    HAS_ASYNC_REST_SUPPORT_IN_CORE = True
except ImportError as e:  # pragma: NO COVER
    raise ImportError("async rest transport requires google-api-core >= 2.20.0. Install google-api-core using `pip install google-api-core==2.35.0`.") from e

from google.protobuf import json_format

import json  # type: ignore
import dataclasses
from typing import Any, Callable, Tuple, Optional, Sequence, Union


from google.protobuf import empty_pb2  # type: ignore
from google.showcase_v1beta1.types import messaging
from google.longrunning import operations_pb2  # type: ignore


from .rest_base import _BaseMessagingRestTransport

from .base import DEFAULT_CLIENT_INFO as BASE_DEFAULT_CLIENT_INFO

try:
    OptionalRetry = Union[retries.AsyncRetry, gapic_v1.method._MethodDefault, None]
except AttributeError:  # pragma: NO COVER
    OptionalRetry = Union[retries.AsyncRetry, object, None]  # type: ignore

DEFAULT_CLIENT_INFO = gapic_v1.client_info.ClientInfo(
    gapic_version=BASE_DEFAULT_CLIENT_INFO.gapic_version,
    grpc_version=None,
    rest_version=google.auth.__version__
)

@dataclasses.dataclass
class AsyncMessagingRestStub:
    _session: AsyncAuthorizedSession
    _host: str

class AsyncMessagingRestTransport(_BaseMessagingRestTransport):
    """Asynchronous REST backend transport for Messaging.

    A simple messaging service that implements chat rooms and
    profile posts.
    This messaging service showcases the features that API clients
    generated by gapic-generators implement.

    This class defines the same methods as the primary client, so the
    primary client can load the underlying transport implementation
    and call it.

    It sends JSON representations of protocol buffers over HTTP/1.1
    """
    def __init__(self,
            *,
            host: str = 'localhost:7469',
            credentials: Optional[ga_credentials_async.Credentials] = None,
            client_info: gapic_v1.client_info.ClientInfo = DEFAULT_CLIENT_INFO,
            url_scheme: str = 'https',
            ) -> None:
        """Instantiate the transport.

       NOTE: This async REST transport functionality is currently in a beta
       state (preview). We welcome your feedback via a GitHub issue in
       this library's repository. Thank you!

        Args:
            host (Optional[str]):
                 The hostname to connect to (default: 'localhost:7469').
            credentials (Optional[google.auth.aio.credentials.Credentials]): The
                authorization credentials to attach to requests. These
                credentials identify the application to the service; if none
                are specified, the client will attempt to ascertain the
                credentials from the environment.
            client_info (google.api_core.gapic_v1.client_info.ClientInfo):
                The client info used to send a user-agent string along with
                API requests. If ``None``, then default info will be used.
                Generally, you only need to set this if you are developing
                your own client library.
            url_scheme (str): the protocol scheme for the API endpoint.  Normally
                "https", but for testing or local servers,
                "http" can be specified.
        """
        # Run the base constructor
        super().__init__(
            host=host,
            credentials=credentials,
            client_info=client_info,
            always_use_jwt_access=False,
            url_scheme=url_scheme,
            api_audience=None
        )
        self._session = AsyncAuthorizedSession(self._credentials)  # type: ignore
        self._wrap_with_kind = True
        self._prep_wrapped_messages(client_info)

    def _prep_wrapped_messages(self, client_info):
        """ Precompute the wrapped methods, overriding the base class method to use async wrappers."""
        self._wrapped_methods = {
            self.create_room: self._wrap_method(
                self.create_room,
                default_timeout=None,
                client_info=client_info,
            ),
            self.get_room: self._wrap_method(
                self.get_room,
                default_retry=retries.AsyncRetry(
                    initial=0.1,
                    maximum=3.0,
                    multiplier=2,
                    predicate=retries.if_exception_type(
                        core_exceptions.ServiceUnavailable,
                        core_exceptions.Unknown,
                    ),
                    deadline=10.0,
                ),
                default_timeout=10.0,
                client_info=client_info,
            ),
            self.update_room: self._wrap_method(
                self.update_room,
                default_timeout=None,
                client_info=client_info,
            ),
            self.delete_room: self._wrap_method(
                self.delete_room,
                default_timeout=None,
                client_info=client_info,
            ),
            self.list_rooms: self._wrap_method(
                self.list_rooms,
                default_retry=retries.AsyncRetry(
                    initial=0.1,
                    maximum=3.0,
                    multiplier=2,
                    predicate=retries.if_exception_type(
                        core_exceptions.ServiceUnavailable,
                        core_exceptions.Unknown,
                    ),
                    deadline=10.0,
                ),
                default_timeout=10.0,
                client_info=client_info,
            ),
            self.create_blurb: self._wrap_method(
                self.create_blurb,
                default_timeout=None,
                client_info=client_info,
            ),
            self.get_blurb: self._wrap_method(
                self.get_blurb,
                default_retry=retries.AsyncRetry(
                    initial=0.1,
                    maximum=3.0,
                    multiplier=2,
                    predicate=retries.if_exception_type(
                        core_exceptions.ServiceUnavailable,
                        core_exceptions.Unknown,
                    ),
                    deadline=10.0,
                ),
                default_timeout=10.0,
                client_info=client_info,
            ),
            self.update_blurb: self._wrap_method(
                self.update_blurb,
                default_timeout=None,
                client_info=client_info,
            ),
            self.delete_blurb: self._wrap_method(
                self.delete_blurb,
                default_timeout=None,
                client_info=client_info,
            ),
            self.list_blurbs: self._wrap_method(
                self.list_blurbs,
                default_retry=retries.AsyncRetry(
                    initial=0.1,
                    maximum=3.0,
                    multiplier=2,
                    predicate=retries.if_exception_type(
                        core_exceptions.ServiceUnavailable,
                        core_exceptions.Unknown,
                    ),
                    deadline=10.0,
                ),
                default_timeout=10.0,
                client_info=client_info,
            ),
            self.search_blurbs: self._wrap_method(
                self.search_blurbs,
                default_retry=retries.AsyncRetry(
                    initial=0.1,
                    maximum=3.0,
                    multiplier=2,
                    predicate=retries.if_exception_type(
                        core_exceptions.ServiceUnavailable,
                        core_exceptions.Unknown,
                    ),
                    deadline=10.0,
                ),
                default_timeout=10.0,
                client_info=client_info,
            ),
            self.stream_blurbs: self._wrap_method(
                self.stream_blurbs,
                default_timeout=None,
                client_info=client_info,
            ),
            self.send_blurbs: self._wrap_method(
                self.send_blurbs,
                default_timeout=None,
                client_info=client_info,
            ),
            self.connect: self._wrap_method(
                self.connect,
                default_retry=retries.AsyncRetry(
                    initial=0.1,
                    maximum=3.0,
                    multiplier=2,
                    predicate=retries.if_exception_type(
                        core_exceptions.ServiceUnavailable,
                        core_exceptions.Unknown,
                    ),
                    deadline=10.0,
                ),
                default_timeout=10.0,
                client_info=client_info,
            ),
        }

    def _wrap_method(self, func, *args, **kwargs):
        if self._wrap_with_kind:  # pragma: NO COVER
            kwargs["kind"] = self.kind
        return gapic_v1.method_async.wrap_method(func, *args, **kwargs)

    class _Connect(_BaseMessagingRestTransport._BaseConnect, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.Connect")

        async def __call__(self,
                    request: messaging.ConnectRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ) -> rest_streaming_async.AsyncResponseIterator:
                raise NotImplementedError(
                    "Method Connect is not available over REST transport"
                )

    class _CreateBlurb(_BaseMessagingRestTransport._BaseCreateBlurb, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.CreateBlurb")

        @staticmethod
        async def _get_response(
            host,
            metadata,
            query_params,
            session,
            timeout,
            transcoded_request,
            body=None):

            uri = transcoded_request['uri']
            method = transcoded_request['method']
            headers = dict(metadata)
            headers['Content-Type'] = 'application/json'
            response = await getattr(session, method)(
                "{host}{uri}".format(host=host, uri=uri),
                timeout=timeout,
                headers=headers,
                params=rest_helpers.flatten_query_params(query_params, strict=True),
                data=body,
                )
            return response

        async def __call__(self,
                    request: messaging.CreateBlurbRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ) -> messaging.Blurb:
            r"""Call the create blurb method over HTTP.

            Args:
                request (~.messaging.CreateBlurbRequest):
                    The request object. The request message for the
                google.showcase.v1beta1.Messaging\CreateBlurb
                method.
                retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                    should be retried.
                timeout (float): The timeout for this request.
                metadata (Sequence[Tuple[str, str]]): Strings which should be
                    sent along with the request as metadata.

            Returns:
                ~.messaging.Blurb:
                    This protocol buffer message
                represents a blurb sent to a chat room
                or posted on a user profile.

            """

            http_options = _BaseMessagingRestTransport._BaseCreateBlurb._get_http_options()
            transcoded_request = _BaseMessagingRestTransport._BaseCreateBlurb._get_transcoded_request(http_options, request)

            body = _BaseMessagingRestTransport._BaseCreateBlurb._get_request_body_json(transcoded_request)

            # Jsonify the query params
            query_params = _BaseMessagingRestTransport._BaseCreateBlurb._get_query_params_json(transcoded_request)

            # Send the request
            response = await AsyncMessagingRestTransport._CreateBlurb._get_response(self._host, metadata, query_params, self._session, timeout, transcoded_request, body)

            # In case of error, raise the appropriate core_exceptions.GoogleAPICallError exception
            # subclass.
            if response.status_code >= 400:
                content = await response.read()
                payload = json.loads(content.decode('utf-8'))
                request_url = "{host}{uri}".format(host=self._host, uri=transcoded_request['uri'])
                method = transcoded_request['method']
                raise core_exceptions.format_http_response_error(response, method, request_url, payload)  # type: ignore

            # Return the response
            resp = messaging.Blurb()
            pb_resp = messaging.Blurb.pb(resp)
            content = await response.read()
            json_format.Parse(content, pb_resp, ignore_unknown_fields=True)
            return resp

    class _CreateRoom(_BaseMessagingRestTransport._BaseCreateRoom, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.CreateRoom")

        @staticmethod
        async def _get_response(
            host,
            metadata,
            query_params,
            session,
            timeout,
            transcoded_request,
            body=None):

            uri = transcoded_request['uri']
            method = transcoded_request['method']
            headers = dict(metadata)
            headers['Content-Type'] = 'application/json'
            response = await getattr(session, method)(
                "{host}{uri}".format(host=host, uri=uri),
                timeout=timeout,
                headers=headers,
                params=rest_helpers.flatten_query_params(query_params, strict=True),
                data=body,
                )
            return response

        async def __call__(self,
                    request: messaging.CreateRoomRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ) -> messaging.Room:
            r"""Call the create room method over HTTP.

            Args:
                request (~.messaging.CreateRoomRequest):
                    The request object. The request message for the
                google.showcase.v1beta1.Messaging\CreateRoom
                method.
                retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                    should be retried.
                timeout (float): The timeout for this request.
                metadata (Sequence[Tuple[str, str]]): Strings which should be
                    sent along with the request as metadata.

            Returns:
                ~.messaging.Room:
                    A chat room.
            """

            http_options = _BaseMessagingRestTransport._BaseCreateRoom._get_http_options()
            transcoded_request = _BaseMessagingRestTransport._BaseCreateRoom._get_transcoded_request(http_options, request)

            body = _BaseMessagingRestTransport._BaseCreateRoom._get_request_body_json(transcoded_request)

            # Jsonify the query params
            query_params = _BaseMessagingRestTransport._BaseCreateRoom._get_query_params_json(transcoded_request)

            # Send the request
            response = await AsyncMessagingRestTransport._CreateRoom._get_response(self._host, metadata, query_params, self._session, timeout, transcoded_request, body)

            # In case of error, raise the appropriate core_exceptions.GoogleAPICallError exception
            # subclass.
            if response.status_code >= 400:
                content = await response.read()
                payload = json.loads(content.decode('utf-8'))
                request_url = "{host}{uri}".format(host=self._host, uri=transcoded_request['uri'])
                method = transcoded_request['method']
                raise core_exceptions.format_http_response_error(response, method, request_url, payload)  # type: ignore

            # Return the response
            resp = messaging.Room()
            pb_resp = messaging.Room.pb(resp)
            content = await response.read()
            json_format.Parse(content, pb_resp, ignore_unknown_fields=True)
            return resp

    class _DeleteBlurb(_BaseMessagingRestTransport._BaseDeleteBlurb, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.DeleteBlurb")

        @staticmethod
        async def _get_response(
            host,
            metadata,
            query_params,
            session,
            timeout,
            transcoded_request,
            body=None):

            uri = transcoded_request['uri']
            method = transcoded_request['method']
            headers = dict(metadata)
            headers['Content-Type'] = 'application/json'
            response = await getattr(session, method)(
                "{host}{uri}".format(host=host, uri=uri),
                timeout=timeout,
                headers=headers,
                params=rest_helpers.flatten_query_params(query_params, strict=True),
                )
            return response

        async def __call__(self,
                    request: messaging.DeleteBlurbRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ):
            r"""Call the delete blurb method over HTTP.

            Args:
                request (~.messaging.DeleteBlurbRequest):
                    The request object. The request message for the
                google.showcase.v1beta1.Messaging\DeleteBlurb
                method.
                retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                    should be retried.
                timeout (float): The timeout for this request.
                metadata (Sequence[Tuple[str, str]]): Strings which should be
                    sent along with the request as metadata.
            """

            http_options = _BaseMessagingRestTransport._BaseDeleteBlurb._get_http_options()
            transcoded_request = _BaseMessagingRestTransport._BaseDeleteBlurb._get_transcoded_request(http_options, request)

            # Jsonify the query params
            query_params = _BaseMessagingRestTransport._BaseDeleteBlurb._get_query_params_json(transcoded_request)

            # Send the request
            response = await AsyncMessagingRestTransport._DeleteBlurb._get_response(self._host, metadata, query_params, self._session, timeout, transcoded_request)

            # In case of error, raise the appropriate core_exceptions.GoogleAPICallError exception
            # subclass.
            if response.status_code >= 400:
                content = await response.read()
                payload = json.loads(content.decode('utf-8'))
                request_url = "{host}{uri}".format(host=self._host, uri=transcoded_request['uri'])
                method = transcoded_request['method']
                raise core_exceptions.format_http_response_error(response, method, request_url, payload)  # type: ignore

    class _DeleteRoom(_BaseMessagingRestTransport._BaseDeleteRoom, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.DeleteRoom")

        @staticmethod
        async def _get_response(
            host,
            metadata,
            query_params,
            session,
            timeout,
            transcoded_request,
            body=None):

            uri = transcoded_request['uri']
            method = transcoded_request['method']
            headers = dict(metadata)
            headers['Content-Type'] = 'application/json'
            response = await getattr(session, method)(
                "{host}{uri}".format(host=host, uri=uri),
                timeout=timeout,
                headers=headers,
                params=rest_helpers.flatten_query_params(query_params, strict=True),
                )
            return response

        async def __call__(self,
                    request: messaging.DeleteRoomRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ):
            r"""Call the delete room method over HTTP.

            Args:
                request (~.messaging.DeleteRoomRequest):
                    The request object. The request message for the
                google.showcase.v1beta1.Messaging\DeleteRoom
                method.
                retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                    should be retried.
                timeout (float): The timeout for this request.
                metadata (Sequence[Tuple[str, str]]): Strings which should be
                    sent along with the request as metadata.
            """

            http_options = _BaseMessagingRestTransport._BaseDeleteRoom._get_http_options()
            transcoded_request = _BaseMessagingRestTransport._BaseDeleteRoom._get_transcoded_request(http_options, request)

            # Jsonify the query params
            query_params = _BaseMessagingRestTransport._BaseDeleteRoom._get_query_params_json(transcoded_request)

            # Send the request
            response = await AsyncMessagingRestTransport._DeleteRoom._get_response(self._host, metadata, query_params, self._session, timeout, transcoded_request)

            # In case of error, raise the appropriate core_exceptions.GoogleAPICallError exception
            # subclass.
            if response.status_code >= 400:
                content = await response.read()
                payload = json.loads(content.decode('utf-8'))
                request_url = "{host}{uri}".format(host=self._host, uri=transcoded_request['uri'])
                method = transcoded_request['method']
                raise core_exceptions.format_http_response_error(response, method, request_url, payload)  # type: ignore

    class _GetBlurb(_BaseMessagingRestTransport._BaseGetBlurb, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.GetBlurb")

        @staticmethod
        async def _get_response(
            host,
            metadata,
            query_params,
            session,
            timeout,
            transcoded_request,
            body=None):

            uri = transcoded_request['uri']
            method = transcoded_request['method']
            headers = dict(metadata)
            headers['Content-Type'] = 'application/json'
            response = await getattr(session, method)(
                "{host}{uri}".format(host=host, uri=uri),
                timeout=timeout,
                headers=headers,
                params=rest_helpers.flatten_query_params(query_params, strict=True),
                )
            return response

        async def __call__(self,
                    request: messaging.GetBlurbRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ) -> messaging.Blurb:
            r"""Call the get blurb method over HTTP.

            Args:
                request (~.messaging.GetBlurbRequest):
                    The request object. The request message for the
                google.showcase.v1beta1.Messaging\GetBlurb
                method.
                retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                    should be retried.
                timeout (float): The timeout for this request.
                metadata (Sequence[Tuple[str, str]]): Strings which should be
                    sent along with the request as metadata.

            Returns:
                ~.messaging.Blurb:
                    This protocol buffer message
                represents a blurb sent to a chat room
                or posted on a user profile.

            """

            http_options = _BaseMessagingRestTransport._BaseGetBlurb._get_http_options()
            transcoded_request = _BaseMessagingRestTransport._BaseGetBlurb._get_transcoded_request(http_options, request)

            # Jsonify the query params
            query_params = _BaseMessagingRestTransport._BaseGetBlurb._get_query_params_json(transcoded_request)

            # Send the request
            response = await AsyncMessagingRestTransport._GetBlurb._get_response(self._host, metadata, query_params, self._session, timeout, transcoded_request)

            # In case of error, raise the appropriate core_exceptions.GoogleAPICallError exception
            # subclass.
            if response.status_code >= 400:
                content = await response.read()
                payload = json.loads(content.decode('utf-8'))
                request_url = "{host}{uri}".format(host=self._host, uri=transcoded_request['uri'])
                method = transcoded_request['method']
                raise core_exceptions.format_http_response_error(response, method, request_url, payload)  # type: ignore

            # Return the response
            resp = messaging.Blurb()
            pb_resp = messaging.Blurb.pb(resp)
            content = await response.read()
            json_format.Parse(content, pb_resp, ignore_unknown_fields=True)
            return resp

    class _GetRoom(_BaseMessagingRestTransport._BaseGetRoom, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.GetRoom")

        @staticmethod
        async def _get_response(
            host,
            metadata,
            query_params,
            session,
            timeout,
            transcoded_request,
            body=None):

            uri = transcoded_request['uri']
            method = transcoded_request['method']
            headers = dict(metadata)
            headers['Content-Type'] = 'application/json'
            response = await getattr(session, method)(
                "{host}{uri}".format(host=host, uri=uri),
                timeout=timeout,
                headers=headers,
                params=rest_helpers.flatten_query_params(query_params, strict=True),
                )
            return response

        async def __call__(self,
                    request: messaging.GetRoomRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ) -> messaging.Room:
            r"""Call the get room method over HTTP.

            Args:
                request (~.messaging.GetRoomRequest):
                    The request object. The request message for the
                google.showcase.v1beta1.Messaging\GetRoom
                method.
                retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                    should be retried.
                timeout (float): The timeout for this request.
                metadata (Sequence[Tuple[str, str]]): Strings which should be
                    sent along with the request as metadata.

            Returns:
                ~.messaging.Room:
                    A chat room.
            """

            http_options = _BaseMessagingRestTransport._BaseGetRoom._get_http_options()
            transcoded_request = _BaseMessagingRestTransport._BaseGetRoom._get_transcoded_request(http_options, request)

            # Jsonify the query params
            query_params = _BaseMessagingRestTransport._BaseGetRoom._get_query_params_json(transcoded_request)

            # Send the request
            response = await AsyncMessagingRestTransport._GetRoom._get_response(self._host, metadata, query_params, self._session, timeout, transcoded_request)

            # In case of error, raise the appropriate core_exceptions.GoogleAPICallError exception
            # subclass.
            if response.status_code >= 400:
                content = await response.read()
                payload = json.loads(content.decode('utf-8'))
                request_url = "{host}{uri}".format(host=self._host, uri=transcoded_request['uri'])
                method = transcoded_request['method']
                raise core_exceptions.format_http_response_error(response, method, request_url, payload)  # type: ignore

            # Return the response
            resp = messaging.Room()
            pb_resp = messaging.Room.pb(resp)
            content = await response.read()
            json_format.Parse(content, pb_resp, ignore_unknown_fields=True)
            return resp

    class _ListBlurbs(_BaseMessagingRestTransport._BaseListBlurbs, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.ListBlurbs")

        async def __call__(self,
                    request: messaging.ListBlurbsRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ) -> messaging.ListBlurbsResponse:
                raise NotImplementedError(
                    "Method ListBlurbs is not available over REST transport"
                )

    class _ListRooms(_BaseMessagingRestTransport._BaseListRooms, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.ListRooms")

        async def __call__(self,
                    request: messaging.ListRoomsRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ) -> messaging.ListRoomsResponse:
                raise NotImplementedError(
                    "Method ListRooms is not available over REST transport"
                )

    class _SearchBlurbs(_BaseMessagingRestTransport._BaseSearchBlurbs, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.SearchBlurbs")

        async def __call__(self,
                    request: messaging.SearchBlurbsRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ) -> operations_pb2.Operation:
                raise NotImplementedError(
                    "Method SearchBlurbs is not available over REST transport"
                )

    class _SendBlurbs(_BaseMessagingRestTransport._BaseSendBlurbs, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.SendBlurbs")

        async def __call__(self,
                    request: messaging.CreateBlurbRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ) -> messaging.SendBlurbsResponse:
                raise NotImplementedError(
                    "Method SendBlurbs is not available over REST transport"
                )

    class _StreamBlurbs(_BaseMessagingRestTransport._BaseStreamBlurbs, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.StreamBlurbs")

        @staticmethod
        async def _get_response(
            host,
            metadata,
            query_params,
            session,
            timeout,
            transcoded_request,
            body=None):

            uri = transcoded_request['uri']
            method = transcoded_request['method']
            headers = dict(metadata)
            headers['Content-Type'] = 'application/json'
            response = await getattr(session, method)(
                "{host}{uri}".format(host=host, uri=uri),
                timeout=timeout,
                headers=headers,
                params=rest_helpers.flatten_query_params(query_params, strict=True),
                data=body,
                )
            return response

        async def __call__(self,
                    request: messaging.StreamBlurbsRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ) -> rest_streaming_async.AsyncResponseIterator:
            r"""Call the stream blurbs method over HTTP.

            Args:
                request (~.messaging.StreamBlurbsRequest):
                    The request object. The request message for the
                google.showcase.v1beta1.Messaging\StreamBlurbs
                method.
                retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                    should be retried.
                timeout (float): The timeout for this request.
                metadata (Sequence[Tuple[str, str]]): Strings which should be
                    sent along with the request as metadata.

            Returns:
                ~.messaging.StreamBlurbsResponse:
                    The response message for the
                google.showcase.v1beta1.Messaging\StreamBlurbs
                method.

            """

            http_options = _BaseMessagingRestTransport._BaseStreamBlurbs._get_http_options()
            transcoded_request = _BaseMessagingRestTransport._BaseStreamBlurbs._get_transcoded_request(http_options, request)

            body = _BaseMessagingRestTransport._BaseStreamBlurbs._get_request_body_json(transcoded_request)

            # Jsonify the query params
            query_params = _BaseMessagingRestTransport._BaseStreamBlurbs._get_query_params_json(transcoded_request)

            # Send the request
            response = await AsyncMessagingRestTransport._StreamBlurbs._get_response(self._host, metadata, query_params, self._session, timeout, transcoded_request, body)

            # In case of error, raise the appropriate core_exceptions.GoogleAPICallError exception
            # subclass.
            if response.status_code >= 400:
                content = await response.read()
                payload = json.loads(content.decode('utf-8'))
                request_url = "{host}{uri}".format(host=self._host, uri=transcoded_request['uri'])
                method = transcoded_request['method']
                raise core_exceptions.format_http_response_error(response, method, request_url, payload)  # type: ignore

            # Return the response
            resp = rest_streaming_async.AsyncResponseIterator(response, messaging.StreamBlurbsResponse)
            return resp

    class _UpdateBlurb(_BaseMessagingRestTransport._BaseUpdateBlurb, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.UpdateBlurb")

        @staticmethod
        async def _get_response(
            host,
            metadata,
            query_params,
            session,
            timeout,
            transcoded_request,
            body=None):

            uri = transcoded_request['uri']
            method = transcoded_request['method']
            headers = dict(metadata)
            headers['Content-Type'] = 'application/json'
            response = await getattr(session, method)(
                "{host}{uri}".format(host=host, uri=uri),
                timeout=timeout,
                headers=headers,
                params=rest_helpers.flatten_query_params(query_params, strict=True),
                data=body,
                )
            return response

        async def __call__(self,
                    request: messaging.UpdateBlurbRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ) -> messaging.Blurb:
            r"""Call the update blurb method over HTTP.

            Args:
                request (~.messaging.UpdateBlurbRequest):
                    The request object. The request message for the
                google.showcase.v1beta1.Messaging\UpdateBlurb
                method.
                retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                    should be retried.
                timeout (float): The timeout for this request.
                metadata (Sequence[Tuple[str, str]]): Strings which should be
                    sent along with the request as metadata.

            Returns:
                ~.messaging.Blurb:
                    This protocol buffer message
                represents a blurb sent to a chat room
                or posted on a user profile.

            """

            http_options = _BaseMessagingRestTransport._BaseUpdateBlurb._get_http_options()
            transcoded_request = _BaseMessagingRestTransport._BaseUpdateBlurb._get_transcoded_request(http_options, request)

            body = _BaseMessagingRestTransport._BaseUpdateBlurb._get_request_body_json(transcoded_request)

            # Jsonify the query params
            query_params = _BaseMessagingRestTransport._BaseUpdateBlurb._get_query_params_json(transcoded_request)

            # Send the request
            response = await AsyncMessagingRestTransport._UpdateBlurb._get_response(self._host, metadata, query_params, self._session, timeout, transcoded_request, body)

            # In case of error, raise the appropriate core_exceptions.GoogleAPICallError exception
            # subclass.
            if response.status_code >= 400:
                content = await response.read()
                payload = json.loads(content.decode('utf-8'))
                request_url = "{host}{uri}".format(host=self._host, uri=transcoded_request['uri'])
                method = transcoded_request['method']
                raise core_exceptions.format_http_response_error(response, method, request_url, payload)  # type: ignore

            # Return the response
            resp = messaging.Blurb()
            pb_resp = messaging.Blurb.pb(resp)
            content = await response.read()
            json_format.Parse(content, pb_resp, ignore_unknown_fields=True)
            return resp

    class _UpdateRoom(_BaseMessagingRestTransport._BaseUpdateRoom, AsyncMessagingRestStub):
        def __hash__(self):
            return hash("AsyncMessagingRestTransport.UpdateRoom")

        @staticmethod
        async def _get_response(
            host,
            metadata,
            query_params,
            session,
            timeout,
            transcoded_request,
            body=None):

            uri = transcoded_request['uri']
            method = transcoded_request['method']
            headers = dict(metadata)
            headers['Content-Type'] = 'application/json'
            response = await getattr(session, method)(
                "{host}{uri}".format(host=host, uri=uri),
                timeout=timeout,
                headers=headers,
                params=rest_helpers.flatten_query_params(query_params, strict=True),
                data=body,
                )
            return response

        async def __call__(self,
                    request: messaging.UpdateRoomRequest, *,
                    retry: OptionalRetry=gapic_v1.method.DEFAULT,
                    timeout: Optional[float]=None,
                    metadata: Sequence[Tuple[str, str]]=(),
                    ) -> messaging.Room:
            r"""Call the update room method over HTTP.

            Args:
                request (~.messaging.UpdateRoomRequest):
                    The request object. The request message for the
                google.showcase.v1beta1.Messaging\UpdateRoom
                method.
                retry (google.api_core.retry_async.AsyncRetry): Designation of what errors, if any,
                    should be retried.
                timeout (float): The timeout for this request.
                metadata (Sequence[Tuple[str, str]]): Strings which should be
                    sent along with the request as metadata.

            Returns:
                ~.messaging.Room:
                    A chat room.
            """

            http_options = _BaseMessagingRestTransport._BaseUpdateRoom._get_http_options()
            transcoded_request = _BaseMessagingRestTransport._BaseUpdateRoom._get_transcoded_request(http_options, request)

            body = _BaseMessagingRestTransport._BaseUpdateRoom._get_request_body_json(transcoded_request)

            # Jsonify the query params
            query_params = _BaseMessagingRestTransport._BaseUpdateRoom._get_query_params_json(transcoded_request)

            # Send the request
            response = await AsyncMessagingRestTransport._UpdateRoom._get_response(self._host, metadata, query_params, self._session, timeout, transcoded_request, body)

            # In case of error, raise the appropriate core_exceptions.GoogleAPICallError exception
            # subclass.
            if response.status_code >= 400:
                content = await response.read()
                payload = json.loads(content.decode('utf-8'))
                request_url = "{host}{uri}".format(host=self._host, uri=transcoded_request['uri'])
                method = transcoded_request['method']
                raise core_exceptions.format_http_response_error(response, method, request_url, payload)  # type: ignore

            # Return the response
            resp = messaging.Room()
            pb_resp = messaging.Room.pb(resp)
            content = await response.read()
            json_format.Parse(content, pb_resp, ignore_unknown_fields=True)
            return resp

    @property
    def connect(self) -> Callable[
            [messaging.ConnectRequest],
            messaging.StreamBlurbsResponse]:
        return self._Connect(self._session, self._host)  # type: ignore

    @property
    def create_blurb(self) -> Callable[
            [messaging.CreateBlurbRequest],
            messaging.Blurb]:
        return self._CreateBlurb(self._session, self._host)  # type: ignore

    @property
    def create_room(self) -> Callable[
            [messaging.CreateRoomRequest],
            messaging.Room]:
        return self._CreateRoom(self._session, self._host)  # type: ignore

    @property
    def delete_blurb(self) -> Callable[
            [messaging.DeleteBlurbRequest],
            empty_pb2.Empty]:
        return self._DeleteBlurb(self._session, self._host)  # type: ignore

    @property
    def delete_room(self) -> Callable[
            [messaging.DeleteRoomRequest],
            empty_pb2.Empty]:
        return self._DeleteRoom(self._session, self._host)  # type: ignore

    @property
    def get_blurb(self) -> Callable[
            [messaging.GetBlurbRequest],
            messaging.Blurb]:
        return self._GetBlurb(self._session, self._host)  # type: ignore

    @property
    def get_room(self) -> Callable[
            [messaging.GetRoomRequest],
            messaging.Room]:
        return self._GetRoom(self._session, self._host)  # type: ignore

    @property
    def list_blurbs(self) -> Callable[
            [messaging.ListBlurbsRequest],
            messaging.ListBlurbsResponse]:
        return self._ListBlurbs(self._session, self._host)  # type: ignore

    @property
    def list_rooms(self) -> Callable[
            [messaging.ListRoomsRequest],
            messaging.ListRoomsResponse]:
        return self._ListRooms(self._session, self._host)  # type: ignore

    @property
    def search_blurbs(self) -> Callable[
            [messaging.SearchBlurbsRequest],
            operations_pb2.Operation]:
        return self._SearchBlurbs(self._session, self._host)  # type: ignore

    @property
    def send_blurbs(self) -> Callable[
            [messaging.CreateBlurbRequest],
            messaging.SendBlurbsResponse]:
        return self._SendBlurbs(self._session, self._host)  # type: ignore

    @property
    def stream_blurbs(self) -> Callable[
            [messaging.StreamBlurbsRequest],
            messaging.StreamBlurbsResponse]:
        return self._StreamBlurbs(self._session, self._host)  # type: ignore

    @property
    def update_blurb(self) -> Callable[
            [messaging.UpdateBlurbRequest],
            messaging.Blurb]:
        return self._UpdateBlurb(self._session, self._host)  # type: ignore

    @property
    def update_room(self) -> Callable[
            [messaging.UpdateRoomRequest],
            messaging.Room]:
        return self._UpdateRoom(self._session, self._host)  # type: ignore

    @property
    def kind(self) -> str:
        return "rest_asyncio"

    async def close(self):
        await self._session.close()
