---
version: 2
workflows:
  version: 2
  tests:
    jobs:
      - unit
      - docs
jobs:
  unit:
    docker:
      - image: 'python:3.6'
    steps:
      - checkout
      - run:
          name: Install nox and codecov.
          command: pip install nox-automation codecov
      - run:
          name: Run unit tests.
          command: nox -s unit
      - run:
          name: Submit coverage data to codecov.
          command: codecov
          when: always
  docs:
    docker:
      - image: 'python:3.6'
    steps:
      - checkout
      - run:
          name: Install nox.
          command: pip install nox-automation
      - run:
          name: Build the documentation.
          command: nox -s docs
